# Generated by Django 3.2.5 on 2021-12-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ourTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('teamMemberPhoto', models.ImageField(blank=True, null=True, upload_to='t4eamMemberPhoto')),
            ],
        ),
    ]
