# Generated by Django 3.2.5 on 2021-12-01 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0003_patientreviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='homepageBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainHeading', models.CharField(max_length=100)),
                ('subHeading', models.CharField(max_length=200)),
                ('context', models.TextField()),
                ('bannerImage', models.ImageField(upload_to='bannerImage')),
            ],
        ),
    ]
