# Generated by Django 3.2.5 on 2021-12-04 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0005_patientappointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='patientFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedbackText', models.TextField()),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientapp.patientappointment')),
            ],
        ),
    ]
