# Generated by Django 3.2.5 on 2021-12-04 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0006_patientfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientappointment',
            name='doctorAccept',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientappointment',
            name='doctorCompleted',
            field=models.BooleanField(default=False),
        ),
    ]
