# Generated by Django 3.2.5 on 2021-12-04 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0007_auto_20211204_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientappointment',
            name='patientFeedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
