# Generated by Django 3.2.5 on 2021-12-04 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0008_patientappointment_patientfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientappointment',
            name='doctorReject',
            field=models.BooleanField(default=False),
        ),
    ]
