# Generated by Django 3.2.5 on 2021-12-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0009_patientappointment_doctorreject'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientappointment',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
