# Generated by Django 3.2.6 on 2021-12-13 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0011_disease_predicted_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease_predicted_data',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
