# Generated by Django 3.2.3 on 2021-12-15 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0012_disease_predicted_data_is_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease_predicted_data',
            name='is_seen',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
